<Project Sdk="Aspire.AppHost.Sdk/13.3.0-preview.1.26153.13">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>8e58bb1b-0645-49ec-a339-a6b95cd8c643</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\VideoEnhancedAgent.Server\VideoEnhancedAgent.Server.csproj" />
    <ProjectReference Include="..\azure-function\azure-function.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.Azure.AIFoundry" Version="13.3.0-preview.1.26153.13" />
    <PackageReference Include="Aspire.Hosting.Azure.Functions" Version="13.3.0-preview.1.26153.13" />
    <PackageReference Include="Aspire.Hosting.Azure.Search" Version="13.3.0-preview.1.26153.13" />
    <PackageReference Include="Aspire.Hosting.Azure.Storage" Version="13.3.0-preview.1.26153.13" />
    <PackageReference Include="Aspire.Hosting.JavaScript" Version="13.3.0-preview.1.26153.13" />
  </ItemGroup>
</Project>
